'use client';

import { useEffect, useRef, useState } from 'react';
import { Html5Qrcode } from 'html5-qrcode';
import { Camera, X, AlertCircle, Loader2, ScanLine, AlertTriangle } from 'lucide-react';

interface QRScannerProps {
  onScan: (data: string) => void;
  onClose: () => void;
  title?: string;
  /**
   * Optional provider for a REAL server-signed QR token used by the
   * "Simulate Camera Scan" fallback (desktop testing when the camera is
   * unavailable/denied). The token is generated by /api/donations/qr so the
   * JWT verification loop stays end-to-end real.
   */
  simulateToken?: () => Promise<string>;
}

export default function QRScanner({
  onScan,
  onClose,
  title = 'Scan QR Code',
  simulateToken,
}: QRScannerProps) {
  const [manualInput, setManualInput] = useState('');
  const [error, setError] = useState<string | null>(null);
  const [starting, setStarting] = useState(true);
  const [scanning, setScanning] = useState(false);
  const [simulating, setSimulating] = useState(false);
  const scannerRef = useRef<Html5Qrcode | null>(null);
  const attemptsRef = useRef(0);
  const firedRef = useRef(false);

  // Start the real rear-camera stream as soon as the modal mounts.
  useEffect(() => {
    const elementId = 'fsai-qr-reader';
    const scanner = new Html5Qrcode(elementId);
    scannerRef.current = scanner;
    let cancelled = false;

    const stopCamera = async () => {
      if (scannerRef.current?.isScanning) {
        try {
          await scannerRef.current.stop();
        } catch {
          // camera already released
        }
      }
    };

    const tryStart = async (facingMode: string) => {
      try {
        await scanner.start(
          { facingMode },
          { fps: 10, qrbox: { width: 240, height: 240 } },
          (decodedText) => {
            if (firedRef.current) return;
            firedRef.current = true;
            setScanning(false);
            // Stop the camera, then hand the raw token string to the caller.
            stopCamera().finally(() => onScan(decodedText));
          },
          () => {
            // Per-frame decode failures (non-QR content) are expected — ignore.
          }
        );
        if (!cancelled) {
          setStarting(false);
          setScanning(true);
        }
      } catch (err) {
        // Rear camera unavailable → fall back to the front camera once.
        if (attemptsRef.current < 1 && facingMode !== 'user') {
          attemptsRef.current += 1;
          await tryStart('user');
          return;
        }
        if (!cancelled) {
          setStarting(false);
          setError(
            'Camera access is denied or unsupported on this device. Use the simulate scan below or enter the code manually.'
          );
        }
      }
    };

    tryStart('environment');

    return () => {
      cancelled = true;
      stopCamera();
      scannerRef.current = null;
    };
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  // Fallback for desktop testing — fetches a REAL JWT from the server so the
  // full verification loop (signature + MongoDB match) is exercised.
  const handleSimulateScan = async () => {
    if (!simulateToken || simulating) return;
    setSimulating(true);
    try {
      const token = await simulateToken();
      if (token) {
        setScanning(false);
        onScan(token);
      } else {
        setError('Could not generate a simulation token. Please try manual entry.');
      }
    } catch {
      setError('Could not generate a simulation token. Please try manual entry.');
    } finally {
      setSimulating(false);
    }
  };

  const handleManualSubmit = () => {
    if (!manualInput.trim()) {
      setError('Please enter QR code data');
      return;
    }
    onScan(manualInput.trim());
  };

  return (
    <div className="fixed inset-0 bg-black/50 backdrop-blur-sm z-50 flex items-center justify-center p-4">
      <div className="bg-white rounded-2xl shadow-2xl w-full max-w-md">
        <div className="p-6 border-b border-gray-100">
          <div className="flex justify-between items-center">
            <h2 className="text-xl font-bold text-gray-900">{title}</h2>
            <button
              onClick={onClose}
              className="p-2 hover:bg-gray-100 rounded-lg transition-colors"
              aria-label="Close scanner"
            >
              <X className="w-5 h-5 text-gray-500" />
            </button>
          </div>
        </div>

        <div className="p-6">
          {/* Live camera viewfinder */}
          <div className="bg-gray-900 rounded-xl overflow-hidden mb-4 relative">
            <div
              id="fsai-qr-reader"
              className="w-full h-72 bg-black [&_video]:!w-full [&_video]:!h-full [&_video]:!object-cover"
            />

            {/* Corner guides */}
            <div className="pointer-events-none absolute inset-0 flex items-center justify-center">
              <div className="w-48 h-48 border-2 border-white/50 rounded-lg relative">
                <div className="absolute top-0 left-0 w-8 h-8 border-t-4 border-l-4 border-green-500 rounded-tl-lg" />
                <div className="absolute top-0 right-0 w-8 h-8 border-t-4 border-r-4 border-green-500 rounded-tr-lg" />
                <div className="absolute bottom-0 left-0 w-8 h-8 border-b-4 border-l-4 border-green-500 rounded-bl-lg" />
                <div className="absolute bottom-0 right-0 w-8 h-8 border-b-4 border-r-4 border-green-500 rounded-br-lg" />
              </div>
            </div>

            {starting && (
              <div className="absolute inset-0 flex items-center justify-center bg-gray-900/80">
                <div className="text-white text-center">
                  <Loader2 className="w-8 h-8 animate-spin mx-auto mb-2" />
                  <p className="text-sm">Starting camera...</p>
                </div>
              </div>
            )}
            {scanning && (
              <div className="absolute bottom-3 inset-x-0 text-center pointer-events-none">
                <span className="inline-flex items-center gap-1.5 px-3 py-1 rounded-full bg-black/60 text-white text-xs">
                  <Camera className="w-3.5 h-3.5" />
                  Scanning…
                </span>
              </div>
            )}
          </div>

          {/* Camera-denied warning banner */}
          {error && (
            <div className="flex items-start gap-2 text-amber-800 bg-amber-50 border border-amber-200 rounded-xl p-3 mb-3">
              <AlertTriangle className="w-4 h-4 flex-shrink-0 mt-0.5" />
              <div className="text-sm">
                <p className="font-semibold">Camera unavailable</p>
                <p className="mt-0.5 text-amber-700">{error}</p>
              </div>
            </div>
          )}

          {/* Simulate fallback (desktop testing) */}
          {error && simulateToken && (
            <button
              onClick={handleSimulateScan}
              disabled={simulating}
              className="w-full py-3 bg-blue-500 text-white font-semibold rounded-xl shadow-lg hover:bg-blue-600 hover:shadow-xl disabled:opacity-50 disabled:cursor-not-allowed transition-all duration-200 mb-4"
            >
              {simulating ? (
                <span className="flex items-center justify-center">
                  <Loader2 className="w-5 h-5 animate-spin mr-2" />
                  Generating token...
                </span>
              ) : (
                <>
                  <ScanLine className="w-5 h-5 inline mr-2" />
                  Simulate Camera Scan
                </>
              )}
            </button>
          )}

          {!error && (
            <p className="text-sm text-gray-500 text-center mb-4">
              Point your camera at the QR code to verify instantly
            </p>
          )}

          {/* Divider */}
          <div className="flex items-center gap-4 my-4">
            <div className="flex-1 h-px bg-gray-200" />
            <span className="text-sm text-gray-500">or enter manually</span>
            <div className="flex-1 h-px bg-gray-200" />
          </div>

          {/* Manual Input */}
          <div className="space-y-3">
            <textarea
              value={manualInput}
              onChange={(e) => {
                setManualInput(e.target.value);
                setError(null);
              }}
              placeholder="Paste QR code data here..."
              className="w-full px-4 py-3 border border-gray-200 rounded-xl focus:ring-2 focus:ring-green-500 focus:border-transparent resize-none"
              rows={3}
            />

            <button
              onClick={handleManualSubmit}
              className="w-full py-3 bg-gray-100 text-gray-700 font-semibold rounded-xl hover:bg-gray-200 transition-colors"
            >
              Submit Manual Entry
            </button>
          </div>
        </div>
      </div>
    </div>
  );
}
